// you can add your action type here
export const SET_ERROR="SET_ERROR"
export const SET_ERROR_SUCCESS="SET_ERROR_SUCCESS"
export const GET_PRODUCTS="GET_PRODUCTS"
export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS"
export const GET_PRODUCT_DETAIL="GET_PRODUCT_DETAIL"
export const GET_PRODUCT_DETAIL_SUCCESS="GET_PRODUCT_DETAIL_SUCCESS"
export const CREATE_PRODUCT="CREATE_PRODUCT"
export const CREATE_PRODUCT_SUCCESS="CREATE_PRODUCT_SUCCESS"
export const GET_CATEGORIES="GET_CATEGORIES"
export const GET_CATEGORIES_SUCCESS="GET_CATEGORIES_SUCCESS"
export const GET_CATEGORY_BY_ID="GET_CATEGORY_BY_ID"
export const GET_CATEGORY_BY_ID_SUCCESS="GET_CATEGORY_BY_ID_SUCCESS"

